name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1 #выполняем команды на actionee
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          debug: true
          script: |
            set -e 
            cd ~/app
            git fetch origin
            git checkout main
            git reset --hard origin/main
            docker compose up -d --build
            docker compose ps
            